version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres         # nome do usuário
      POSTGRES_PASSWORD: admin        # senha do usuário
      POSTGRES_DB: api_rest         # nome do banco de dados
    ports:
      - "5432:5432"
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data  # pasta local para persistência

